PB_URL = "http://127.0.0.1:8090"  # albo gdzie masz PB

POSTS_COLLECTION = "posts"
COMMENTS_COLLECTION = "comments"
POST_STATS_COLLECTION = "post_stats"
POST_VIEWS_COLLECTION = "post_views"
SERIES_COLLECTION = "series"

RECAPTCHA_SITE_KEY = "6LdbiV8sAAAAAF8LDZM0A8DDHWOD-DXhI-v7Dc7q"
RECAPTCHA_SECRET_KEY = "6LdbiV8sAAAAAOZ0nKuYXgpZqSVXrJAvnUB_OImB"


